name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        run: ./ahk-compile-toolset/AutoHotkey64.exe ./distribution.ahk

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/ahko.zip
            dist/version.txt
          generate_release_notes: true
